# Project information
site_name: "RTEU CE205 Data Structures Course Notes"
docs_dir: docs  # Where to find the markdown files
site_dir: site  # Where to output the HTML files
site_author: 'Asst. Prof. Dr. Uğur CORUH'
site_url: 'https://ucoruh.github.io/ce205-data-structures/'
site_description: 'Course Notes for Software Developers'

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/ucoruh/ce205-data-structures'
edit_uri: 'https://github.com/ucoruh/ce205-data-structures/edit/main/docs/'

# Copyright
copyright: Copyright &copy; 2006 - 2024 Recep Tayyip Erdoğan University

# Configuration
theme:
  name: material
  custom_dir: docs/overrides

  favicon: images/favicon.png

  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    logo: logo  # Adjust the file name if necessary
  
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  
  # Static files  
  static_templates:
   - 404.html
    
  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest

  palette:
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: brown
      accent: brown
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono

# Customization
extra:
  annotate:
    json: [.s2]
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_RTEU_CE205
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target=_blank>feedback form</a>.
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics: Google Analytics
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ucoruh
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ugurcoruh/
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/ucoruh/
    - icon: fontawesome/regular/id-card
      link: https://dblp.org/pid/230/0394.html
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/my-orcid?orcid=0000-0003-4193-8401
    - icon: fontawesome/brands/google
      link: https://scholar.google.com/citations?user=KIU4ltMAAAAJ&hl=tr

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: ucoruh
      repo: ce100-algorithms-and-programming-II
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - codehilite:
      guess_lang: true

# Plugins
plugins:
  - mkdocs-simple-hooks:
      hooks:
        on_env: "hooks:on_env"
  - external-markdown
  - mkdocs-video
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - i18n:
      docs_structure: suffix
      reconfigure_material: true
      reconfigure_search: true
      fallback_to_default: true
      languages:
        - locale: en
          name: "English"
          build: true
          default: true
          site_name: "RTEU CE100 Algorithms and Programming-II Course Notes"
        - locale: tr
          name: "Türkçe"
          build: true
          site_name: "RTEU CE100 Algoritmalar ve Programlama-II Ders Notları"
          nav_translations:
              Home: "Anasayfa"
              Syllabus: "Ders Programı"
              Course Modules: "Ders Modülleri"
              Week-1 (Introduction to Data Structures): "Hafta-1 (Veri Yapılarına Giriş)"
              Week-2 (Linked Lists): "Hafta-2 (Bağlı Listeler)"
              Week-3 (Stacks and Queues): "Hafta-3 (Yığınlar ve Kuyruklar)"
              Week-4 (Tree Data Structures): "Hafta-4 (Ağaç Veri Yapıları)"
              Week-5 (Graph Data Structures): "Hafta-5 (Graf Veri Yapıları)"
              Week-6 (Graph Algorithms): "Hafta-6 (Graf Algoritmaları)"
              Week-7 (Search and Hashing): "Hafta-7 (Arama ve Hashleme)"
              Week-8 (Midterm): "Hafta-8 (Ara Sınav)"
              Week-9 (Sorting): "Hafta-9 (Sıralama)"
              Week-10 (Advanced Tree Structures): "Hafta-10 (İleri Ağaç Yapıları)"
              Week-11 (String Data Structures): "Hafta-11 (Dize Veri Yapıları)"
              Week-12 (String Algorithms): "Hafta-12 (Dize Algoritmaları)"
              Week-13 (Sequential and Direct File Organization): "Hafta-13 (Sıralı ve Doğrudan Dosya Düzeni)"
              Week-14 (Direct File Organization and B Tree Structures for File): "Hafta-14 (Dosya için Doğrudan Dosya ve B Ağaç Yapıları)"
              Week-15 (Hashing Techniques, String Matching, Trie, Secondary Key Retrieval, File Sorting): "Hafta-15 (Hashleme Teknikleri, Dize Eşleştirme, Trie, İkincil Anahtar Erişimi, Dosya Sıralama)"
              Week-16 (Final): "Hafta-16 (Final)"
              License: "Lisans"
              Resume: "Özgeçmiş"
              Changelog: "Revizyonlar"
  - tags:
      tags_file: tags.md
  - minify:
      minify_html: true
      htmlmin_opts:
        remove_comments: true
  - git-revision-date-localized:
      fallback_to_build_date: true
      type: timeago
  - git-authors:
      sort_authors_by: contribution
  - git-committers:
      repository: ucoruh/ce205-data-structures
      docs_path: docs/
      branch: main
      token: !ENV MKDOCS_GIT_COMMITTERS_APIKEY
  - macros

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Page tree (for navigation)
nav:
  - Home: index.md
  - Syllabus: syllabus/syllabus.md
  - Course Modules:
    - Week-1 (Introduction to Data Structures): week-1-intro/ce205-week-1-intro.md
    - Week-2 (Linked Lists): week-2-linkedlist/ce205-week-2-linkedlist.md
    - Week-3 (Stacks and Queues): week-3-stack/ce205-week-3-stack.md
    - Week-4 (Tree Data Structures): week-4-tree-structures/ce205-week-4-tree-structures.md
    - Week-5 (Grapy Data Structures): week-5-graph-structures/ce205-week-5-graph-structures.md
    - Week-6 (Graph Algorithms): week-6-graph-algorithms/ce205-week-6-graph-algorithms.md
    - Week-7 (Search and Hashing): week-7-search-hashing/ce205-week-7-search-hashing.md
    - Week-8 (Midterm): week-8-midterm/ce205-week-8-midterm.md
    - Week-9 (Sorting): week-9-sorting/ce205-week-9-sorting.md
    - Week-10 (Advanced Tree Structures): week-10-advanced-tree-structures/ce205-week-10-advanced-tree-structures.md      
    - Week-11 (String Data Structures): week-11-string-structures/ce205-week-11-string-structures.md 
    - Week-12 (String Algorithms): week-12-string-algorithms/ce205-week-12-string-algorithms.md
    - Week-13 (Sequential and Direct File Organization): week-13-direct-sequential-file/ce205-week-13-direct-sequential-file.md
    - Week-14 (Direct File Organization and B Tree Structures for File): week-14-direct-file-b-tree/ce205-week-14-direct-file-b-tree.md
    - Week-15 (Hashing Techniques, String Matching, Trie, Secondary Key Retrival, File Sorting): week-15-hashing-trie/ce205-week-15-hashing-trie.md
    - Week-16 (Final): week-16-final/ce205-week-16-final.md
  - License: license.md
  - Resume: resume/index.md
  - Changelog: changelog/index.md
