# Project information
site_name: "RTEU CE205 Data Structures Course Notes"
site_author: 'Asst. Prof. Dr. Uğur CORUH'
site_url: 'https://ucoruh.github.io/ce205-data-structures/'
site_description: >-
    Course Notes for Software Developers

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/ucoruh/ce205-data-structures'
edit_uri: ""

# Copyright
copyright: Copyleft &copy; 2019 - 2022 Uğur CORUH

#theme:
#    name: material
#   logo: assets/images/favicon.png
#   favicon: images/favicon.png
#   palette:
#       primary: teal
#       accent: pink
#   language: en
#   feature:
#       tabs: true
#   font:
#       text: Roboto
        
# Configuration
theme:
  name: material
  custom_dir: docs/overrides/
  #name: null
  #custom_dir: !ENV [THEME_DIR, "material"]
  
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  
  # Static files
  static_templates:
    - 404.html
    
  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - content.code.annotate
    - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
    
  palette:
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: brown
      accent: brown
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  
#  palette:
#   - media: "(prefers-color-scheme: light)"
#     scheme: default
#     toggle:
#       icon: material/toggle-switch-off-outline
#       name: Switch to dark mode
#   - media: "(prefers-color-scheme: dark)"
#     scheme: slate
#     toggle:
#       icon: material/toggle-switch
#       name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono
  favicon: images/favicon.png
  icon:
    logo: logo
    #logo: assets/images/favicon.png
    
# Customization
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY_CE205
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target=_blank>feedback form</a>.
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics: Google Analytics
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ucoruh
    - icon: fontawesome/brands/bitbucket
      link: https://bitbucket.org/ucoruh/
    - icon: fontawesome/regular/compass
      link: https://www.scopus.com/authid/detail.uri?authorId=57218950743
    - icon: fontawesome/regular/id-card
      link: https://dblp.org/pid/230/0394.html
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/ucoruh/
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/my-orcid?orcid=0000-0003-4193-8401
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ugurcoruh/
    - icon: fontawesome/regular/moon
      link: https://publons.com/researcher/1540204/ugur-coruh/
    - icon: fontawesome/brands/google
      link: https://scholar.google.com/citations?user=KIU4ltMAAAAJ&hl=tr
    - icon: fontawesome/regular/clipboard
      link: https://avesis.erdogan.edu.tr/ugur.coruh
    - icon: fontawesome/regular/user-circle
      link: https://www.ugurcoruh.com/
      
# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - git-revision-date-localized
  - minify:
      minify_html: false

extra_javascript:
  - javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
# Page tree
nav:
  - Home: index.md
  - Syllabus: syllabus/syllabus.md
  - Course Modules:
    - Week-1 (Introduction to Data Structures): week-1-intro/ce205-week-1-intro.md
    - Week-2 (Linked Lists): week-2-linkedlist/ce205-week-2-linkedlist.md
    - Week-3 (Stacks and Queues): week-3-stack/ce205-week-3-stack.md
    - Week-4 (Tree Data Structures): week-4-tree-structures/ce205-week-4-tree-structures.md
    - Week-5 (Grapy Data Structures): week-5-graph-structures/ce205-week-5-graph-structures.md
    - Week-6 (Graph Algorithms): week-6-graph-algorithms/ce205-week-6-graph-algorithms.md
    - Week-7 (Search and Hashing): week-7-search-hashing/ce205-week-7-search-hashing.md
    - Week-8 (Midterm): week-8-midterm/ce205-week-8-midterm.md
    - Week-9 (Sorting): week-9-sorting/ce205-week-9-sorting.md
    - Week-10 (Advanced Tree Structures): week-10-advanced-tree-structures/ce205-week-10-advanced-tree-structures.md      
    - Week-11 (String Data Structures): week-11-string-structures/ce205-week-11-string-structures.md 
    - Week-12 (String Algorithms): week-12-string-algorithms/ce205-week-12-string-algorithms.md
    - Week-13 (Sequential and Direct File Organization): week-13-direct-sequential-file/ce205-week-13-direct-sequential-file.md
    - Week-14 (Direct File Organization and B Tree Structures for File): week-14-direct-file-b-tree/ce205-week-14-direct-file-b-tree.md
    - Week-15 (Hashing Techniques, String Matching, Trie, Secondary Key Retrival, File Sorting): week-15-hashing-trie/ce205-week-15-hashing-trie.md
    - Week-16 (Final): week-16-final/ce205-week-16-final.md
  - License: license.md
  - Changelog: changelog/index.md



