rem use github gitignore templates via API
rem https://github.com/sloria/gig

rem INSTALL
rem pip install -U gig 

rem API URLS 
rem API_URL = "https://api.github.com/gitignore/templates"
rem GLOBAL_URL = "https://api.github.com/repos/github/gitignore/contents/Global/"
rem TEMPLATE_URL = "https://raw.github.com/github/gitignore/master"
rem HEADER = "########## Generated by gig ###########\n"

rem USAGE
rem gig list
rem gig list --global
rem gig Python Ruby > .gitignore
rem gig C C++ CMake Java VisualStudio

@echo off
setlocal

echo Get the current directory
set "currentDir=%CD%"

echo Change the current working directory to the script directory
cd /d "%~dp0"

echo Change the working directory to the parent folder
cd ..


REM API URL for GitHub Gitignore templates
set API_URL=https://www.toptal.com/developers/gitignore/api/c,csharp,vs,visualstudio,visualstudiocode,java,maven,c++,cmake,eclipse,netbeans
REM Set the output file name
set OUTPUT_FILE=.gitignore

REM Check if .gitignore already exists
if exist "%OUTPUT_FILE%" (
    echo .gitignore already exists, skipping generation.
) else (    
	REM Download the API results using curl
	curl -s -o %OUTPUT_FILE% %API_URL%
    if %ERRORLEVEL% neq 0 (
        echo Failed to download .gitignore file from %API_URL%
        exit /b 1
    )
    echo Downloaded .gitignore file from %API_URL% and saved as %OUTPUT_FILE%

    REM Append '**/desktop.ini' to .gitignore
    echo **/desktop.ini >> %OUTPUT_FILE%
    echo Appended '**/desktop.ini' to %OUTPUT_FILE%
)

echo Revert to the original directory
cd "%currentDir%"

pause
@endlocal



